#!/usr/bin/env python
import os
import sys
import shutil
from SCons.Script import Copy

env = SConscript("./../../godot-cpp/SConstruct")

# Pass playfab_platform=windows (default) or playfab_platform=$Platform
playfab_platform = ARGUMENTS.get("playfab_platform", "windows").lower()
if playfab_platform not in ("windows", "gdk", "android", "ios", "mac", "linux"):
    print("ERROR: playfab_platform must be 'windows', 'gdk', 'android', 'ios', 'mac', or 'linux'")
    Exit(1)

env.Append(CPPPATH=["src/", "include/", "include/httpClient/", "include/playfab/", "include/playfab/core/", "include/playfab/multiplayer/", "include/playfab/party/", "include/playfab/services/"])
env.Append(SCONS_CXX_STANDARD="c++17")
env.Append(LIBPATH=["lib/"])
print("Building for platform: " + playfab_platform)
if playfab_platform == "windows":
    env.Append(LIBS=["libHttpClient.Win32", "PartyWin", "PlayFabCore.Win32", "PlayFabMultiplayerWin", "PlayFabServices.Win32"])
    dlls = [
        "./lib/libHttpClient.Win32.dll",
        "./lib/PartyWin.dll",
        "./lib/PlayFabCore.Win32.dll",
        "./lib/PlayFabMultiplayerWin.dll",
        "./lib/PlayFabServices.Win32.dll"
    ]
elif playfab_platform == "gdk":  # gdk
    env.Append(LIBS=["libHttpClient.GDK", "PartyXboxLive", "PlayFabCore.GDK", "PlayFabMultiplayerGDK", "PlayFabServices.GDK"])
    dlls = [
        "./lib/libHttpClient.GDK.dll",
        "./lib/PartyXboxLive.dll",
        "./lib/PlayFabCore.GDK.dll",
        "./lib/PlayFabMultiplayerGDK.dll",
        "./lib/PlayFabServices.GDK.dll"
    ]
elif playfab_platform == "android":
    env.Append(LIBS=["libHttpClient.Android", "PartyAndroid", "PlayFabCore.Android", "PlayFabMultiplayerAndroid", "PlayFabServices.Android"])
    dlls = [
        "./lib/libHttpClient.Android.so",
        "./lib/PartyAndroid.so",
        "./lib/PlayFabCore.Android.so",
        "./lib/PlayFabMultiplayerAndroid.so",
        "./lib/PlayFabServices.Android.so"
    ]
elif playfab_platform == "ios":
    env.Append(LIBS=["libHttpClient.iOS", "PartyiOS", "PlayFabCore.iOS", "PlayFabMultiplayeriOS", "PlayFabServices.iOS"])
    dlls = [
        "./lib/libHttpClient.iOS.dylib",
        "./lib/PartyiOS.dylib",
        "./lib/PlayFabCore.iOS.dylib",
        "./lib/PlayFabMultiplayeriOS.dylib",
        "./lib/PlayFabServices.iOS.dylib"
    ]
elif playfab_platform == "mac":
    env.Append(LIBS=["libHttpClient.Mac", "PartyMac", "PlayFabCore.Mac", "PlayFabMultiplayerMac", "PlayFabServices.Mac"])
    dlls = [
        "./lib/libHttpClient.Mac.dylib",
        "./lib/PartyMac.dylib",
        "./lib/PlayFabCore.Mac.dylib",
        "./lib/PlayFabMultiplayerMac.dylib",
        "./lib/PlayFabServices.Mac.dylib"
    ]
else:
    # Assume Linux
    env.Append(LIBS=["libHttpClient.Linux", "PartyLinux", "PlayFabCore.Linux", "PlayFabMultiplayerLinux", "PlayFabServices.Linux"])
    dlls = [
        "./lib/libHttpClient.Linux.so",
        "./lib/PartyLinux.so",
        "./lib/PlayFabCore.Linux.so",
        "./lib/PlayFabMultiplayerLinux.so",
        "./lib/PlayFabServices.Linux.so"
    ]

dlls += [
    "./src/gdexample.gdextension",
]

sources = Glob("src/*.cpp")

# Ensure the demo/bin directory exists
if not os.path.exists("demo/bin"):
    os.makedirs("demo/bin")

# Ensure the DLLs are copied to the target directory
for dll in dlls:
    target = os.path.join("demo/bin/", os.path.basename(dll))
    print("Copying " + dll + " to " + target)
    if os.path.exists(dll):
        shutil.copy2(dll, target)
    else:
        print("WARNING: DLL not found: " + dll)

library = env.SharedLibrary(
    "demo/bin/libgdxexample{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source = sources,
)

Default(library)