<#
.SYNOPSIS
    Stages a native-free Godot host that runs only the editor-tool GUT suites.

.DESCRIPTION
    The `godot_gdk_editortools` addon is pure GDScript. Its suites normally run
    inside the GDK coverage host (tests\godot\gdk), which needs the native GDK
    extension and therefore a full native build. This script builds a throwaway
    host that runs those same suites with no GDExtension DLLs at all, so PR
    gates can validate editor-tool changes without building the native addons.

    The staged host contains:
      - project.godot               (no autoloads, no editor plugins, no GDK settings)
      - addons\godot_gdk_editortools (copied from the addon source of truth)
      - addons\godot_gdk_tests       (gdk_test_base.gd + test_env.gd; plain GDScript)
      - addons\gut                   (third_party\Gut, or Gut-4.5 for Godot 4.5.x)
      - tests\editortools\**, tests\test_editortools.gd, tests\fixtures\packaging\**
      - the GDK host's root logo PNGs (the packaging suites back up/regenerate them)

    Run the suites with the orchestrator, for example:
        pwsh -File tools\ci\prepare_editortools_host.ps1
        pwsh -File tools\run_all_tests.ps1 -Hosts build\editortools-host -SkipBuild -SkipDoctest -SkipParse

.PARAMETER HostDir
    Repo-relative destination. Recreated from scratch. Must stay under build\.
    Default: build\editortools-host.

.PARAMETER GodotVersion
    Godot version the host will run on (e.g. 4.6.2 or 4.5.1). Selects the GUT
    mirror: 4.5.x uses third_party\Gut-4.5, anything else uses third_party\Gut.
    Default: 4.6.

.OUTPUTS
    Writes the repo-relative host path to the pipeline and, when GITHUB_OUTPUT is
    set, a `host` output.
#>
[CmdletBinding()]
param(
    [string]$HostDir = 'build\editortools-host',
    [string]$GodotVersion = '4.6'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$normalizedHost = ($HostDir -replace '/', '\').TrimEnd('\')
if ([System.IO.Path]::IsPathRooted($normalizedHost) -or $normalizedHost -match '(^|\\)\.\.(\\|$)' -or
    $normalizedHost -notmatch '^build\\[^\\]') {
    throw "HostDir must be a repo-relative path under build\ (got '$HostDir')."
}
$hostRoot = Join-Path $repoRoot $normalizedHost

$gdkHost = Join-Path $repoRoot 'tests\godot\gdk'
$want45 = $GodotVersion -match '^4\.5(\.|-|$)'
$gutSource = Join-Path $repoRoot $(if ($want45) { 'third_party\Gut-4.5\addons\gut' } else { 'third_party\Gut\addons\gut' })
if (-not (Test-Path (Join-Path $gutSource 'gut_cmdln.gd'))) {
    throw "GUT sources not found at $gutSource. Run: git submodule update --init third_party/Gut third_party/Gut-4.5"
}

$sources = [ordered]@{
    'addons\godot_gdk_editortools' = Join-Path $repoRoot 'addons\godot_gdk_editortools'
    'addons\gut'                   = $gutSource
    'tests\editortools'            = Join-Path $gdkHost 'tests\editortools'
    'tests\fixtures\packaging'     = Join-Path $gdkHost 'tests\fixtures\packaging'
}
foreach ($entry in $sources.GetEnumerator()) {
    if (-not (Test-Path $entry.Value)) { throw "Missing editor-tool host source: $($entry.Value)" }
}

if (Test-Path $hostRoot) { Remove-Item $hostRoot -Recurse -Force }
New-Item -ItemType Directory -Path $hostRoot -Force | Out-Null

foreach ($entry in $sources.GetEnumerator()) {
    $dest = Join-Path $hostRoot $entry.Key
    New-Item -ItemType Directory -Path (Split-Path $dest -Parent) -Force | Out-Null
    Copy-Item $entry.Value $dest -Recurse -Force
}

# The addon source may carry a build-time bin\ or .godot cache in a dev tree; neither belongs here.
Get-ChildItem $hostRoot -Recurse -Directory -Force -Filter '.godot' | Remove-Item -Recurse -Force

$baseDest = Join-Path $hostRoot 'addons\godot_gdk_tests'
New-Item -ItemType Directory -Path $baseDest -Force | Out-Null
foreach ($base in 'gdk_test_base.gd', 'test_env.gd') {
    Copy-Item (Join-Path $repoRoot "addons\godot_gdk\tests_support\bases\$base") $baseDest -Force
}

Copy-Item (Join-Path $gdkHost 'tests\test_editortools.gd') (Join-Path $hostRoot 'tests') -Force
Get-ChildItem $gdkHost -File -Filter '*.png' | Copy-Item -Destination $hostRoot -Force

$feature = if ($want45) { '4.5' } else { '4.6' }
@"
; Generated by tools/ci/prepare_editortools_host.ps1 -- do not commit.
; Native-free host for the godot_gdk_editortools GUT suites.
config_version=5

[application]

config/name="Godot GDK Editor Tools Tests"
config/features=PackedStringArray("$feature")
"@ | Set-Content -Path (Join-Path $hostRoot 'project.godot') -Encoding utf8NoBOM

$dlls = @(Get-ChildItem $hostRoot -Recurse -File -Include '*.dll', '*.gdextension')
if ($dlls.Count -gt 0) {
    throw "Editor-tool host must be native-free but contains: $($dlls.FullName -join ', ')"
}

$suiteCount = @(Get-ChildItem (Join-Path $hostRoot 'tests') -Recurse -File -Filter 'test_*.gd').Count
Write-Host "Staged native-free editor-tool host at $normalizedHost ($suiteCount suites, GUT $(if ($want45) { '4.5' } else { 'default' }))."
if ($env:GITHUB_OUTPUT) {
    "host=$($normalizedHost -replace '\\', '/')" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
}
$normalizedHost
